### ISSUE TITLE
imageCaptureBuild Image rotate

### ISSUE THREAD

**Issue by developerGM** [ChochaNaresh/FilePicker#44]
Hi,
I am testing your library, really usefully, thanks

I am using `new FilePicker.Builder(mContext).imageCaptureBuild(new ImageCaptureConfig())`
and I am receiving an image with a 90° rotation

**Comment by ChochaNaresh** [comment]
Hi @developerGM 
Please provide more details about the library version and phone details.

**Comment by developerGM** [comment]
Hi, 
the library version is `0.2.2`

Mobile phone: Xiaomi 9T, Android 10

**Comment by developerGM** [comment]
Hi @ChochaNaresh 
any news about this issue?

**Comment by ChochaNaresh** [comment]
Hi @developerGM 

You can use the following code to find the rotation, then save the rotation picture as a new file to resolve your issue.

`
String selectedImage = data.getData();
String[] filePathColumn = {MediaStore.Images.Media.DATA};

Cursor cursor = getContentResolver().query(selectedImage, filePathColumn, null, null, null);
cursor.moveToFirst();

int columnIndex = cursor.getColumnIndex(filePathColumn[0]);
filePath = cursor.getString(columnIndex);
cursor.close();

int rotateImage = getCameraPhotoOrientation(MyActivity.this, selectedImage, filePath);
`

`
public int getCameraPhotoOrientation(Context context, Uri imageUri, String imagePath){
    int rotate = 0;
    try {
        context.getContentResolver().notifyChange(imageUri, null);
        File imageFile = new File(imagePath);

        ExifInterface exif = new ExifInterface(imageFile.getAbsolutePath());
        int orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_NORMAL);

        switch (orientation) {
        case ExifInterface.ORIENTATION_ROTATE_270:
            rotate = 270;
            break;
        case ExifInterface.ORIENTATION_ROTATE_180:
            rotate = 180;
            break;
        case ExifInterface.ORIENTATION_ROTATE_90:
            rotate = 90;
            break;
        }

        Log.i("RotateImage", "Exif orientation: " + orientation);
        Log.i("RotateImage", "Rotate value: " + rotate);
    } catch (Exception e) {
        e.printStackTrace();
    }
    return rotate;
}
`

**Comment by ChochaNaresh** [comment]
limited conversation
