### ISSUE TITLE
Config camera facing option

### ISSUE THREAD

**Issue by bagusajilgq** [ChochaNaresh/FilePicker#52]
Whenever my app open the camera UI, it's always using the front camera. How do I force to use the back camera? Couldn't find the config inside `ImageCaptureConfig`.

Thank you in advance for this library.

**Comment by ChochaNaresh** [comment]
Thank you for suggesting
It is not functioning as intended and has opened an issue on the Google issue tracker:  https://issuetracker.google.com/issues/36924444

**Comment by bagusajilgq** [comment]
In some image picker library, it working by manually changing the camera facing inside camera app so the app will use the last camera. I wonder if this also possible because the camera is always reset back to the front camera, or is it only in my phone (Asus Zenfone 10)?

**Comment by ChochaNaresh** [comment]
limited conversation
