### ISSUE TITLE
open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by DiFilosofa** [ChochaNaresh/FilePicker#55]
Hi i'm trying to use the library to pick the file and upload as multipart with retrofit. 
If I pick the file in Documents or Images, folder the upload goes through fine.
But when I pick the file directly from /Downloads folder it gave me the error

`java.io.FileNotFoundException: /storage/emulated/0/Download/2mb.png: open failed: EACCES (Permission denied)`

I'm testing with Android 13

Upon the demo app, it can still display the images if I do the same thing. 
Any idea what could be the issue, thank you in advance

```
val mimeTypes: List<String> = listOf("image/jpeg", "image/png", "image/jpg", "application/pdf")

FilePicker.Builder(requireContext())
                .pickDocumentFileBuild(
                    DocumentFilePickerConfig(allowMultiple = false, mMimeTypes = mimeTypes),
                )
```

**Comment by ChochaNaresh** [comment]
Hi @DiFilosofa 

please test in sempal app
